export enum RoutePolicies {
    FIND_ALL_MESSAGES = 'FIND_ALL_MESSAGES',
    FIND_ONE_MESSAGE = 'FIND_ONE_MESSAGE',
    CREATE_MESSAGE = 'CREATE_MESSAGE',
    UPDATE_MESSAGE = 'UPDATE_MESSAGE',
    DELETE_MESSAGE = 'DELETE_MESSAGE',

    CREATE_PERSON = 'CREATE_PERSON',
    FIND_ONE_PERSON = 'FIND_ONE_PERSON',
    UPDATE_PERSON = 'UPDATE_PERSON',
    DELETE_PERSON = 'DELETE_PERSON',
    FIND_ALL_PEOPLE = 'FIND_ALL_PEOPLE',
}
